### ISSUE TITLE
Advanced indexing output contains unexpected 0s

### ISSUE THREAD

**Issue by manopapad** [nv-legate/cupynumeric#1215]
See https://github.com/nv-legate/discussion/discussions/6 for full context. Copying here one of the bugs reported by @IlgarBaghishov:

Another issue we have now is with values of the masked `a_train` matrix. If I print the last rows of the `a_train` matrix instead of first rows after masking operation I get zeros like this:

```
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
```

Seems like this advanced indexing operation did not finish fully and thus left some of the rows as zeros.

We also tried cupynumeric.compress but it just crashes silently.

@IlgarBaghishov could you please share the full script (updated with printing the last rows rather than the first rows), and how you're running it?

**Comment by IlgarBaghishov** [comment]
You can use this example code:

```
import cupynumeric as cnp

a = cnp.random.rand(3_000_000, 1500)
train_mask = cnp.random.rand(a.shape[0]) < 0.5
a_train = a[train_mask]

print(a_train[:3,:10])   # This line print random values
print(a_train[-3:,:10])  # This line results in zeros
```

I am running this on NVIDIA's Grace Hopper nodes on Vista supercomputer at TACC. Here is the nvidia-smi output:
```
Mon Jul  7 22:37:25 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.124.06             Driver Version: 570.124.06     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GH200 120GB             On  |   00000009:01:00.0 Off |                    0 |
| N/A   25C    P0             86W /  900W |       1MiB /  97871MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

This is the command I use to run the python script:
`legate --fbmem 93000 test_zeros.py`

Please let me know if you need any other information and thank you so much for your help!

**Comment by ravankhidirov** [comment]
Hi team @manopapad @ipdemes !
Thanks for documenting this issue. As a temporary workaround, we have been using small batches for masking which seems to prevent zero rows. But we would love to see if you have any progress on this issue. Thanks in advance for your support.

**Comment by kharvey2** [comment]
Hi @ravankhidirov! I tried reproducing the issue on the latest packages, and `print(a_train[-3:,:10])` in the example you shared, is not printing all zeros for me. Can you share the output you get when running `legate-issue`? Also, could you try running the code using the latest version of the Conda package to see if the issue persists? You can find instructions [here](https://nv-legate.github.io/legate/installation.html) under the "Installing Conda Packages" section for how to install the _nightly top-of-tree builds_. This will ensure you're using the most updated version of our packages!

**Comment by lightsighter** [comment]
Do we know if this is using indirect copy tasks or using Legion copy operations to perform the advanced indexing?

**Comment by ravankhidirov** [comment]
Hi team! @manopapad @ipdemes @lightsighter Thanks for responses

We tested the same script using the latest nightly top-of-tree Legate packages as suggested. The good news is that the issue with zeroed rows during indexing is no longer present. However, we're now encountering an out-of-memory error during execution.

Here are the details:

The code we are trying to run is as follows:

#### **Python Script (`t4.py`)**

```python
from legate.io.hdf5 import from_file
import cupynumeric as np
import time

a = np.asarray(from_file("/work/10745/ravankhidirov/vista/data/be_data/X.hdf5", dataset_name="X"))
train_mask = np.random.rand(a.shape[0]) < 0.5
test_mask = ~train_mask

print("a shape:", a.shape, flush=True)
memory_bytes = a.size * a.itemsize
memory_mb = memory_bytes / (1024 ** 2)
print(f"a memory usage: {memory_mb:.2f} MB", flush=True)


a_train = a[train_mask]
print("done train", flush = True)
print(a_train[:2,:10], flush = True)
a_test = a[test_mask]
print("done test", flush = True)
print(a_test[-2:,:10], flush = True)
print(a_test[:2,:10], flush = True)

del a
print("deleted", flush = True)

q, r = np.linalg.qr(a_train)
print("did qr", flush = True)
print(q[:2,:10], flush = True)
```


And we are submitting the code using this sh file:

#### **Job Script (`run.sh`)**
```bash
#!/bin/sh
#SBATCH -N 1
#SBATCH -n 72
#SBATCH -o ck1
#SBATCH -p gh-dev
#SBATCH -t 00:30:00
#SBATCH -A CHE25011


nvidia-smi

legate --zcmem 60000 --fbmem 93000 t4.py
```



The error output is:

```
Thu Jul 24 15:23:29 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.124.06             Driver Version: 570.124.06     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GH200 120GB             On  |   00000009:01:00.0 Off |                    0 |
| N/A   25C    P0             78W /  900W |       1MiB /  97871MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
a shape: (3002511, 1595)
a memory usage: 36537.21 MB
done train
[[745.85894958   5.39497333  -2.75847204  25.90323441  -5.22455458
   -4.65501324  -6.09911914  36.55466128  -5.76915657  -5.32533951]
 [-29.95083978  -1.50196355  -4.01499491  89.15857215   1.13277267
   -4.20540298  -3.93647822 -45.31518812   6.3745965   -1.53690685]]
done test
[0 - 4031afecf840]   14.552519 {5}{legate.mapper}: Failed to allocate 19174592360 bytes on memory 1e00000000000002 (of kind SOCKET_MEM) for region requirement(s) {0} of Inline mapping [/home1/10745/ravankhidirov/rdlv/t4.py:20] (UID 47)
[0 - 4031afecf840]   14.554607 {5}{legate.mapper}:   corresponding to a LogicalStore allocated at ["/home1/10745/ravankhidirov/rdlv/t4.py:18", {"file": "/home1/10745/ravankhidirov/rdlv/t4.py", "line": 18}]
[0 - 4031afecf840]   14.554628 {5}{legate.mapper}: There is not enough space because Legate is reserving 57492637742 of the available 101146689536 bytes for the following LogicalStores:
[0 - 4031afecf840]   14.554630 {5}{legate.mapper}: LogicalStore allocated at ["/home1/10745/ravankhidirov/rdlv/t4.py:18", {"file": "/home1/10745/ravankhidirov/rdlv/t4.py", "line": 18}]:
[0 - 4031afecf840]   14.554642 {5}{legate.mapper}:   Instance 4000000000800010 of size 9591526120 covering elements <751024,0>..<1502710,1594>
[0 - 4031afecf840]   14.554644 {5}{legate.mapper}:   Instance 400000000080000f of size 9583066240 covering elements <0,0>..<751023,1594>
[0 - 4031afecf840]   14.554646 {5}{legate.mapper}: LogicalStore allocated at ["/home1/10745/ravankhidirov/rdlv/t4.py:7", {"file": "/home1/10745/ravankhidirov/rdlv/t4.py", "line": 7}]:
[0 - 4031afecf840]   14.554649 {5}{legate.mapper}:   Instance 400000000080000a of size 1501256 covering elements <0>..<1501255>
[0 - 4031afecf840]   14.554650 {5}{legate.mapper}:     created for an operation launched at /home1/10745/ravankhidirov/rdlv/t4.py:7
[0 - 4031afecf840]   14.554651 {5}{legate.mapper}:   Instance 400000000080000c of size 1501255 covering elements <1501256>..<3002510>
[0 - 4031afecf840]   14.554652 {5}{legate.mapper}:     created for an operation launched at /home1/10745/ravankhidirov/rdlv/t4.py:7
[0 - 4031afecf840]   14.554653 {5}{legate.mapper}: LogicalStore allocated at ["/home1/10745/ravankhidirov/rdlv/t4.py:6", {"file": "/home1/10745/ravankhidirov/rdlv/t4.py", "line": 6}]:
[0 - 4031afecf840]   14.554654 {5}{legate.mapper}:   Instance 4000000000800004 of size 1501256 covering elements <0>..<1501255>
[0 - 4031afecf840]   14.554655 {5}{legate.mapper}:     created for an operation launched at /home1/10745/ravankhidirov/rdlv/t4.py:6
[0 - 4031afecf840]   14.554656 {5}{legate.mapper}:   Instance 4000000000800006 of size 1501255 covering elements <1501256>..<3002510>
[0 - 4031afecf840]   14.554657 {5}{legate.mapper}:     created for an operation launched at /home1/10745/ravankhidirov/rdlv/t4.py:6
[0 - 4031afecf840]   14.554658 {5}{legate.mapper}: LogicalStore allocated at (unknown provenance):
[0 - 4031afecf840]   14.554659 {5}{legate.mapper}:   Instance 4000000000800001 of size 19156026560 covering elements <0,0>..<1501255,1594>
[0 - 4031afecf840]   14.554661 {5}{legate.mapper}:   Instance 4000000000800000 of size 19156013800 covering elements <1501256,0>..<3002510,1594>
LEGATE ERROR: ================================================================================
LEGATE ERROR: System: Linux, 5.14.0-362.24.1.el9_3.aarch64+64k, c608-062.vista.tacc.utexas.edu, #1 SMP PREEMPT_DYNAMIC Wed Mar 13 14:27:26 EDT 2024, aarch64
LEGATE ERROR: Legate version: 25.8.0 (e5dde035a7553f596f934c0c28375e0d78c747f5)
LEGATE ERROR: Legion version: 25.8.0 (16441d05a66bdf0f21e271b943a60315f113a55e)
LEGATE ERROR: Configure options: --LEGATE_ARCH=arch-conda --with-python --with-cc=/tmp/conda-croot/legate/_build_env/bin/aarch64-conda-linux-gnu-cc --with-cxx=/tmp/conda-croot/legate/_build_env/bin/aarch64-conda-linux-gnu-c++ --build-march=armv8-a --cmake-generator=Ninja --with-openmp --with-cuda=0 --build-type=release --with-ucx
LEGATE ERROR: LEGATE_CONFIG: --fbmem 93000 --zcmem 60000 --logdir /home1/10745/ravankhidirov/rdlv
LEGATE ERROR: --------------------------------------------------------------------------------
LEGATE ERROR: Exception stack contains 1 exception(s) (bottom-most exception first):
LEGATE ERROR:
LEGATE ERROR: #0 Legate called abort at /tmp/conda-croot/legate/work/src/cpp/legate/mapping/detail/base_mapper.cc:1298 in report_failed_mapping_()
LEGATE ERROR: #0 Out of memory
LEGATE ERROR:
LEGATE ERROR: Stack trace (most recent call first):
LEGATE ERROR: #0  0x0000400037639f5f at /home1/10745/ravankhidirov/miniconda3/envs/legate-nightly/lib/python3.13/site-packages/legate/core/_lib/data/../../../../../../liblegate.so.25.08.00
LEGATE ERROR: #1  0x00004000376339ff at /home1/10745/ravankhidirov/miniconda3/envs/legate-nightly/lib/python3.13/site-packages/legate/core/_lib/data/../../../../../../liblegate.so.25.08.00
LEGATE ERROR: #2  0x0000400037634c4b at /home1/10745/ravankhidirov/miniconda3/envs/legate-nightly/lib/python3.13/site-packages/legate/core/_lib/data/../../../../../../liblegate.so.25.08.00
LEGATE ERROR: #3  0x0000400037634f33 at /home1/10745/ravankhidirov/miniconda3/envs/legate-nightly/lib/python3.13/site-packages/legate/core/_lib/data/../../../../../../liblegate.so.25.08.00
LEGATE ERROR: #4  0x0000400037635643 at /home1/10745/ravankhidirov/miniconda3/envs/legate-nightly/lib/python3.13/site-packages/legate/core/_lib/data/../../../../../../liblegate.so.25.08.00
LEGATE ERROR: #5  0x00004000376358df at /home1/10745/ravankhidirov/miniconda3/envs/legate-nightly/lib/python3.13/site-packages/legate/core/_lib/data/../../../../../../liblegate.so.25.08.00
LEGATE ERROR: #6  0x00004000384dd523 at /home1/10745/ravankhidirov/miniconda3/envs/legate-nightly/lib/python3.13/site-packages/legate/core/_lib/data/../../../../../.././liblegion-legate.so.1
LEGATE ERROR: #7  0x00004000388cfd97 at /home1/10745/ravankhidirov/miniconda3/envs/legate-nightly/lib/python3.13/site-packages/legate/core/_lib/data/../../../../../.././liblegion-legate.so.1
LEGATE ERROR: #8  0x0000400038701607 at /home1/10745/ravankhidirov/miniconda3/envs/legate-nightly/lib/python3.13/site-packages/legate/core/_lib/data/../../../../../.././liblegion-legate.so.1
LEGATE ERROR: #9  0x000040003870d25b at /home1/10745/ravankhidirov/miniconda3/envs/legate-nightly/lib/python3.13/site-packages/legate/core/_lib/data/../../../../../.././liblegion-legate.so.1
LEGATE ERROR: #10 0x00004000389decaf at /home1/10745/ravankhidirov/miniconda3/envs/legate-nightly/lib/python3.13/site-packages/legate/core/_lib/data/../../../../../.././liblegion-legate.so.1
LEGATE ERROR: #11 0x000040003a28a5e3 at /home1/10745/ravankhidirov/miniconda3/envs/legate-nightly/lib/python3.13/site-packages/legate/core/_lib/data/../../../../../.././librealm-legate.so.1
LEGATE ERROR: #12 0x000040003a28a777 at /home1/10745/ravankhidirov/miniconda3/envs/legate-nightly/lib/python3.13/site-packages/legate/core/_lib/data/../../../../../.././librealm-legate.so.1
LEGATE ERROR: #13 0x000040003a288cb7 at /home1/10745/ravankhidirov/miniconda3/envs/legate-nightly/lib/python3.13/site-packages/legate/core/_lib/data/../../../../../.././librealm-legate.so.1
LEGATE ERROR: #14 0x000040003a292d0b at /home1/10745/ravankhidirov/miniconda3/envs/legate-nightly/lib/python3.13/site-packages/legate/core/_lib/data/../../../../../.././librealm-legate.so.1
LEGATE ERROR: #15 0x000040002f8075ff at /usr/lib64/libc.so.6
LEGATE ERROR: ================================================================================

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

As we see, the matrix a is ~36.5 GB. When applying the train mask, it runs fine — but during the test mask, it runs out of memory. It seems the train masking step requires almost double memory, and that memory isn’t released before the test masking starts. We tried these using 25.07.00 and 25.08.00 version and got the same results.


Thanks!!!

**Comment by ipdemes** [comment]
@ravankhidirov can you try increasing `-sysmem` ? The error you are seeing is saying there is no enough CPU memory to perform `print(a_train[:2,:10], flush = True)`. When you call print, the data is being copied from GPUs to CPUs. 
What happen is:
Also, your mrmory allocation is larger on GPU: you allocate ~36.5 GB for `a`, then some amount of memory is allocated  for `train_mask` and ` a_train` as well

**Comment by ravankhidirov** [comment]
Hi @ipdemes . Thanks for the response. We checked your suggestion (by setting sysmem to 128000). So the error we got seemed to be solved. but now we have another issue. The code is like that: 

```python
from legate.io.hdf5 import from_file
import cupynumeric as np
import time

a = np.asarray(from_file("/work/10745/ravankhidirov/vista/data/be_data/X.hdf5", dataset_name="X"))
train_mask = np.random.rand(a.shape[0]) < 0.5
test_mask = ~train_mask

print("a shape:", a.shape, flush=True)
memory_bytes = a.size * a.itemsize
memory_mb = memory_bytes / (1024 ** 2)
print(f"a memory usage: {memory_mb:.2f} MB", flush=True)


a_train = a[train_mask]
print("done train", flush = True)
print(a_train[:2,:10], flush = True)
a_test = a[test_mask]
print("done test", flush = True)
print(a_test[-2:,:10], flush = True)
print(a_test[:2,:10], flush = True)

del a
print("deleted", flush = True)

q, r = np.linalg.qr(a_train)
print("did qr", flush = True)
print(q[:2,:10], flush = True)
```
The output:
```bash
 Fri Jul 25 05:53:37 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.124.06             Driver Version: 570.124.06     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GH200 120GB             On  |   00000009:01:00.0 Off |                    0 |
| N/A   28C    P0             87W /  900W |       1MiB /  97871MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
a shape: (3002511, 1595)
a memory usage: 36537.21 MB
done train
[[745.85894958   5.39497333  -2.75847204  25.90323441  -5.22455458
   -4.65501324  -6.09911914  36.55466128  -5.76915657  -5.32533951]
 [-50.75991209 -12.83782766  -2.68057037  19.69751638   3.11615877
    3.919075   -11.00095446 -47.21921808   0.84424413  -7.46781616]]
done test
[[334.31807188  79.42721303  -4.53969169  32.63012877   0.34772092
   -4.65172078  -3.38637454 -47.22612334   0.46546726   3.37824525]
 [ 58.75702239  -1.42646588  -2.14960546  54.41389479   1.24914396
   -9.21892349   0.69568364  -0.40110467   7.41358594  -0.88882055]]
[[ 1.77765029e+02  2.26405832e+01  1.72682659e-01 -5.08910161e+01
   1.35788812e+00 -3.16507033e+00  2.41284913e+00 -9.01915493e+01
  -3.24156757e+00  9.27116587e+00]
 [ 2.22259083e+01  1.60355332e+00  6.64064275e-02  3.65134463e+00
  -7.89238808e-01 -6.01287543e+00 -2.89352748e+00 -1.70180637e+01
   2.55902176e+00  5.87963264e+00]]
deleted

```
So it hangs after deleting the big matrix. We are allocating around 93 GB GPU, and a matrix has size of 36.5 GB, (mask array has very negligible size ~23 megabayt), While masking we separate this array into train and test (~18GB each) after deleting a matrix there must be enough space for QR operation. However it crashes silently.  Seems like a matrix is not deleted properly and it holds some space.

Thanks!

**Comment by kharvey2** [comment]
Hi @ravankhidirov, would you be able to send us an input file so we can properly reproduce this?

**Comment by IlgarBaghishov** [comment]
Hi @kharvey2, the input file is not necessary. I have tried with a random matrix too and I still get the same silent crash, so you can use this instead of line 5:

```
a = cnp.random.rand(3_000_000, 1500)
```

I think the important part is to have a matrix of size more than 35-40% of the available GPU memory. If you calculate the memory usage, theoretically this code should run successfully with such a matrix but it silently crashed after deleting that original matrix and it does not continue to the QR step. Thank you for your help!

**Comment by ravankhidirov** [comment]
Hi team! @kharvey2 

Just checking in - is there any progress on this issue? Could you reproduce the problem or do you need us to provide more details? Also, is there any method to force to free gpu memory (something similar to cp._default_memory_pool.free_all_blocks() in cupy)? 

Thanks!

**Comment by ipdemes** [comment]
@ravankhidirov @kharvey2 wasn't able to reproduce your issue on our local cluster. She is going to try on a machine with GH200. 
>Also, is there any method to force to free gpu memory

I don't think so. You can delete arrays by `del Array_name`

**Comment by IlgarBaghishov** [comment]
Hi @ipdemes. Thank you for your reply! Please let us know how it goes on GH200.
Also, @kharvey2 about your test on the local cluster. Did the script run fully? What was the size of the matrix and the memory on GPU on your local cluster?
Thank you.

**Comment by ipdemes** [comment]
@IlgarBaghishov : I have just built everything on GH200 and didn't get it to hang.
Could you, please, send me your instructions on how you install everything and how do you run?

**Comment by ipdemes** [comment]
It could also be that the hang is fixed in the most recent conda package. Would you mind building again and re-try.
Here is what I did:
```
conda create -y -p ~/idemeshko/legate_conda_07_29 -c conda-forge    -c legate/label/experimental  cupynumeric
legate ./repro.py
```

**Comment by IlgarBaghishov** [comment]
I have rebuilt and retiried and unfrotunately the original problem persists on the **Vista supercomputer**. 

Here is what I found.

### Environment-Specific Behavior

The outcome depends on where the software environment is created:

* **Created on a login node (no GPU):** The script silently crashes at the QR step. This happens probably because I get a CPU-only version of the library.
* **Created on a compute node (with GPU):** The script runs without the crash, but the last rows of the masked matrix `a_train` are filled with zeros like it was mentioned in the first comment here which we thought was solved with the new build but it turns out it stopped happening because we accidentally created the environment on a login node. This behavior of having zeros is size-dependent.

### Size-Dependency

I have observed three different outcomes based on the size of matrix `a`:

1.  **Small `a`:** The code works correctly. No zeros in the masked array or no silent crash at the QR step. 
2.  **Medium (close to limit) `a`:** The code runs without an error message, but the resulting `a_train` matrix is incorrect, with zero-filled rows at the end.
3.  **Large (above the limit) `a`:** The code fails with a GPU out-of-memory error at the advanced indexing step.

This size-dependent behavior might explain why you could not reproduce the error with a smaller test case. The unexpected zeros in the output for medium-sized matrices are concerning.

### How to Proceed?
However, I also tried this on another cluster and I was not able to reproduce this problem myself on the other cluster. This suggests the issue may be specific to the Vista environment.

Given that this issue seems isolated to one supercomputer, how can I best determine if this is a bug in `cupynumeric` or an issue with the system configuration on Vista (e.g., drivers, CUDA toolkit)?

Could you suggest a minimal test script I could run on both clusters? My goal is to create a clear test case to either share with the Vista technical support or to help you debug further.

### Question: Memory Usage for Advanced Indexing

I also have a quick question about memory usage. Since it worked fine on the other cluster I wanted to see the maximum size of array that will work. I noticed that the operation `a_train = a[train_mask]` requires peak memory of about 2.5 times the size of the original matrix `a`, when the mask `train_mask` selects 50% of the rows (`train_mask` is 1D array).

My expectation was a memory footprint of about 1.5x (1x for `a` + 0.5x for `a_train`). Can you confirm if this 2.5x peak memory usage is expected for boolean mask indexing? If so, could you briefly explain why the temporary memory requirement is so high?

Thank you for your help.

**Comment by manopapad** [comment]
> * **Created on a login node (no GPU):** The script silently crashes at the QR step. This happens probably because I get a CPU-only version of the library.

Still, that shouldn't happen. We have CPU versions of the QR solve algorithm, so those could have been invoked instead. @IlgarBaghishov could you please open an issue on this?

> 2. **Medium (close to limit) `a`:** The code runs without an error message, but the resulting `a_train` matrix is incorrect, with zero-filled rows at the end.
> 
> Given that this issue seems isolated to one supercomputer, how can I best determine if this is a bug in `cupynumeric` or an issue with the system configuration on Vista (e.g., drivers, CUDA toolkit)?
> 
> Could you suggest a minimal test script I could run on both clusters? My goal is to create a clear test case to either share with the Vista technical support or to help you debug further.

First, @kharvey2 could you please try to sweep the input sizes for the given reproducer, to see if you can hit a "medium" case that causes the zero-filled rows at the end? Also CC @amberhassaan as you have seen weird behavior on the same file recently (`advanced_indexing.cu`).

Katherine, please note that it may be necessary to build against Legion:master, to get this bugfix https://gitlab.com/StanfordLegion/legion/-/commit/db9e3dc5028c397dceb8a25e4789381887e8c193.

> I also have a quick question about memory usage. Since it worked fine on the other cluster I wanted to see the maximum size of array that will work. I noticed that the operation `a_train = a[train_mask]` requires peak memory of about 2.5 times the size of the original matrix `a`, when the mask `train_mask` selects 50% of the rows (`train_mask` is 1D array).
> 
> My expectation was a memory footprint of about 1.5x (1x for `a` + 0.5x for `a_train`). Can you confirm if this 2.5x peak memory usage is expected for boolean mask indexing? If so, could you briefly explain why the temporary memory requirement is so high?

The current implementation of the "masked copy" operation first calculates the offsets of the non-zeroes (which uses an array of size equal to that of the original mask array), then creates the output array and uses the offsets to fill it in. Therefore, the memory overhead you quote is expected, under the existing code. See https://github.com/nv-legate/cupynumeric/blob/main/src/cupynumeric/index/advanced_indexing.cu#L120.

But possibly for the case of a dense array we could use `thrust::copy_if`, which has lower memory requirements. WDYT @ipdemes ?

**Comment by ipdemes** [comment]
@manopapad :yes, actually I think we could use thrust::copy_if instead. however I can't guarantee I will have available version to try this week. 
@IlgarBaghishov in the meantime, can you, please, try running your code on multiple gpus to see it you find any other issues? What is the purpose of your investigation so far?

**Comment by manopapad** [comment]
Opened https://github.com/nv-legate/cupynumeric/issues/1226 to track the improved implementation of the "masked copy" operation. Leaving this open to track the investigation of the original bug (unexpected 0s on medium-size arrays).

**Comment by IlgarBaghishov** [comment]
@manopapad Thank you for your reply. I want to test the CPU version of QR on another machine and then create the issue. I am a little busy with a deadline next week. I will do it the week after.
@ipdemes Thank you. Using multiple nodes would likely solve the issue. However, I want to profile the memory usage of each function to see how memory-efficient our scripts are. The main reason I cannot run this on multiple nodes is that the QR algorithm is not available for multi-GPU yet.

**Comment by ipdemes** [comment]
@IlgarBaghishov : sorry for the delay. I am looking at this issue again

**Comment by ipdemes** [comment]
@IlgarBaghishov : I have reproduced the hang with current legate/cupynumeric. However the issue seems to be fixed when updating Legion dependency. I will create a conda package for you to try.

**Comment by apryakhin** [comment]
@ipdemes is there anything you need from me on this issue?

**Comment by ipdemes** [comment]
@IlgarBaghishov @apryakhin 
I have reproduced the issue again and after doing some debugging found  that the hang was at the point when Realm was trying to allocate task-local data for the ADVANCED_INDEXING task. Since we were already using most of the available GPU memory, the allocation couldn't be done and Realm kept waiting for some memory to become available. [After setting the upper bound ](https://github.com/nv-legate/cupynumeric.internal/pull/1070)for the task-local memory in the cupynumeric mapper we are now getting proper error message instead of the hang. 
@IlgarBaghishov : I will let you know when that PR is merged so you can try new package for yourself

**Comment by IlgarBaghishov** [comment]
@ipdemes That is great news! Thank you so much for following up on this. Looking forward to it.

**Comment by ipdemes** [comment]
Hi @IlgarBaghishov : the change has been merged last week. Could you, please, try this conda package out:
`conda install legate/label/experimental::cupynumeric` ?
With this package instead of the hang, you should get error:
```
 LEGION ERROR: Failed to reserve a dynamic memory pool of 53016000032 bytes for leaf task cupynumeric::AdvancedIndexingTask
```
This basically says that there is no enough memory for some task-temporary memory allocation

**Comment by IlgarBaghishov** [comment]
Hi @ipdemes . Thank you so much for fixing this. I tried it and it indeed did not hang or create any 0s at the end of a matrix. The memory requirement is pretty large though. I juts want to make sure if it is expected. It is even higher than what I had in my previous comment. It need 4x the memory of the original array to do advanced indexing, right? So if I have 93000 MiB of GPU memory allocated via --fbmem I can only do indexing of the matrix that takes around 23100 MiB memory because advanced indexing requires additional 3x memory on top of the memory allocated for the matrix.

**Comment by ipdemes** [comment]
Hi @IlgarBaghishov what is happening in the code like `a_train = a[train_mask]` currently : there is temporary array with shape of `a` and `itemsize` of `int*a.ndim` is allocated for advanced indexing operation and new `a_train` array is allocated. so not 4x, of an original array, but rather 2x. the same 2x would need to be allocated for `a_test` as well. Maybe this is where 4x is coming from?

**Comment by IlgarBaghishov** [comment]
Hi @ipdemes 
For some reason I get 4x even if I only do train split without any test split. Here is the python script I use:
```import cupynumeric as np

a = np.random.rand(1_000_000, 1500)
print("size is", a.size * a.itemsize/1024/1024)
train_mask = np.random.rand(a.shape[0]) < 0.5

a_train = a[train_mask]
print(a_train[:3,:10])   # This line prints random values
print(a_train[-3:,:10])  # This line resulted in zeros previously
```

and here is how I run this:
```legate --fbmem 40000 test.py```

Since matrix of this size takes 11444 MiB and if the requirement for advanced indexing was 2x or even 3x it should fit as I have 40000 MiB GPU memory allocated
However, I get this error:
```
[0 - 402d47f8f840]    0.228736 {5}{runtime}: LEGION ERROR: Failed to reserve a dynamic memory pool of 36000000032 bytes for leaf task cupynumeric::AdvancedIndexingTask (UID 7) in GPU_FB_MEM memory. You are actually out of memory here so you'll need to either allocate more memory for this kind of memory when you configure Realm which may necessitate finding a bigger machine. If you want to avoid finding out that you're out of memory this way you should instead use the 'MapperRuntime::acquire_pool' call to make sure that memory can be reserved for all pools in advance. (from file /tmp/conda-croot/legate/work/arch-conda/skbuild_core/_deps/legion-src/runtime/legion/legion_tasks.cc:5025)
Signal 6 received by node 0, process 2848239 (thread 402d47f8f840) - obtaining backtrace
Signal 6 received by process 2848239 (thread 402d47f8f840) at:
stack trace: 18 frames
  [0] = linux-vdso.so.1(__kernel_rt_sigreturn+0) [0x40000a3e07f0]
  [1] = /lib64/libc.so.6(+0x84650) [0x40000a624650]
  [2] = /lib64/libc.so.6(raise+0x1c) [0x40000a5df86c]
  [3] = /lib64/libc.so.6(abort+0xe4) [0x40000a5c7030]
  [4] = /work/08405/ilgar/vista/conda_libraries/cupynumeric/lib/python3.11/site-packages/legate/core/_lib/data/../../../../../.././liblegion-legate.so.1(Legion::Internal::FutureImpl::report_incompatible_accessor(char const*, Realm::RegionInstance)+0) [0x400029b6268c]
  [5] = /work/08405/ilgar/vista/conda_libraries/cupynumeric/lib/python3.11/site-packages/legate/core/_lib/data/../../../../../.././liblegion-legate.so.1(Legion::Internal::SingleTask::create_leaf_memory_pools(Legion::Internal::VariantImpl*, std::map<Realm::Memory, Legion::PoolBounds, std::less<Realm::Memory>, std::allocator<std::pair<Realm::Memory const, Legion::PoolBounds> > >&)+0x130c) [0x400029a23d4c]
  [6] = /work/08405/ilgar/vista/conda_libraries/cupynumeric/lib/python3.11/site-packages/legate/core/_lib/data/../../../../../.././liblegion-legate.so.1(Legion::Internal::SingleTask::finalize_map_task_output(Legion::Mapping::Mapper::MapTaskInput&, Legion::Mapping::Mapper::MapTaskOutput&, Legion::Internal::MustEpochOp*)+0x1c48) [0x400029a46b94]
  [7] = /work/08405/ilgar/vista/conda_libraries/cupynumeric/lib/python3.11/site-packages/legate/core/_lib/data/../../../../../.././liblegion-legate.so.1(Legion::Internal::IndividualTask::finalize_map_task_output(Legion::Mapping::Mapper::MapTaskInput&, Legion::Mapping::Mapper::MapTaskOutput&, Legion::Internal::MustEpochOp*)+0x14) [0x400029a477f4]
  [8] = /work/08405/ilgar/vista/conda_libraries/cupynumeric/lib/python3.11/site-packages/legate/core/_lib/data/../../../../../.././liblegion-legate.so.1(Legion::Internal::SingleTask::invoke_mapper(Legion::Internal::MustEpochOp*)+0x11c) [0x400029a2b31c]
  [9] = /work/08405/ilgar/vista/conda_libraries/cupynumeric/lib/python3.11/site-packages/legate/core/_lib/data/../../../../../.././liblegion-legate.so.1(Legion::Internal::SingleTask::map_all_regions(Legion::Internal::MustEpochOp*, Legion::Internal::TaskOp::DeferMappingArgs const*)+0x27c) [0x400029a2bb1c]
  [10] = /work/08405/ilgar/vista/conda_libraries/cupynumeric/lib/python3.11/site-packages/legate/core/_lib/data/../../../../../.././liblegion-legate.so.1(Legion::Internal::IndividualTask::perform_mapping(Legion::Internal::MustEpochOp*, Legion::Internal::TaskOp::DeferMappingArgs const*)+0x14) [0x400029a2c7fc]
  [11] = /work/08405/ilgar/vista/conda_libraries/cupynumeric/lib/python3.11/site-packages/legate/core/_lib/data/../../../../../.././liblegion-legate.so.1(Legion::Internal::SingleTask::trigger_mapping()+0x14c) [0x400029a0d00c]
  [12] = /work/08405/ilgar/vista/conda_libraries/cupynumeric/lib/python3.11/site-packages/legate/core/_lib/data/../../../../../.././liblegion-legate.so.1(Legion::Internal::Runtime::legion_runtime_task(void const*, unsigned long, void const*, unsigned long, Realm::Processor)+0x634) [0x400029bff424]
  [13] = /work/08405/ilgar/vista/conda_libraries/cupynumeric/lib/python3.11/site-packages/legate/core/_lib/data/../../../../../.././librealm-legate.so.1(+0x7efc58) [0x40002c00fc58]
  [14] = /work/08405/ilgar/vista/conda_libraries/cupynumeric/lib/python3.11/site-packages/legate/core/_lib/data/../../../../../.././librealm-legate.so.1(+0x7efdc8) [0x40002c00fdc8]
  [15] = /work/08405/ilgar/vista/conda_libraries/cupynumeric/lib/python3.11/site-packages/legate/core/_lib/data/../../../../../.././librealm-legate.so.1(+0x7ee230) [0x40002c00e230]
  [16] = /work/08405/ilgar/vista/conda_libraries/cupynumeric/lib/python3.11/site-packages/legate/core/_lib/data/../../../../../.././librealm-legate.so.1(+0x7f8550) [0x40002c018550]
  [17] = /lib64/libc.so.6(+0x27600) [0x40000a5c7600]
```

From the error you can see that advanced indexing requires additional 36000000032 bytes which is exactly 3x of the matrix size. Therefore, it needs 4x in total. If I reduce the matrix to less than 25% of the GPU memory then everything runs fine.

**Comment by manopapad** [comment]
@ipdemes would this be fixed with https://github.com/nv-legate/cupynumeric/issues/1226?

**Comment by ipdemes** [comment]
@IlgarBaghishov yes, your calculations are correct: we are allocating some temporary data inside of the ADVANCED_INDEXING task that resulted in 4x for an upper bound. 

I have just realized that your code could have taken a `fast path` in advanced indexing calculations through using einsum that uses less memory. I will fix the logic in cupynumeric source to do it automatically in the future, but now you can try replacing:
```
a_train = a[train_mask]
a_test = a[test_mask]

```
with
```
a_train = a[train_mask,:]
a_test = a[test_mask, :]
```

Note, to get the new code to take faster path, you would need to build the most recent conda package using legate/experimental label


@manopapad  : yes, we will potentially reduce memory consumption when 1226 is implemented

**Comment by manopapad** [comment]
I'll go ahead and close this one, as the original error is (unexpected 0s) has been resolved. We can use https://github.com/nv-legate/cupynumeric/issues/1226 to track the reduction in memory use.
